export const SET_TITLE = 'SET_TITLE'
export const ALERT = 'ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOGOUT = 'LOGOUT'
